project_id = "cuanladihtpvkmjhvrln"

[functions.send-notification-email]
verify_jwt = false

[functions.check-budgets]
verify_jwt = false

[functions.send-monthly-reports]
verify_jwt = false

[functions.process-recurring-transactions]
verify_jwt = false

[functions.get-investment-transactions]
verify_jwt = false

[functions.api-auth]
verify_jwt = false

[functions.get-accounts]
verify_jwt = false

[functions.get-categories]
verify_jwt = false

[functions.get-recurring]
verify_jwt = false

[functions.get-summary]
verify_jwt = false
