// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-accounts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@2.78.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/list-accounts.ts
var list_accounts_default = defineTool({
  name: "list_accounts",
  title: "List accounts",
  description: "List the signed-in user's bank accounts with their type, bank and current balance.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("accounts").select("id, name, bank, account_type, balance").order("name");
    if (error) return fail(error.message);
    const total = (data ?? []).reduce((s, a) => s + Number(a.balance ?? 0), 0);
    return ok({ accounts: data ?? [], total_balance: Math.round(total * 100) / 100 });
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
var list_categories_default = defineTool2({
  name: "list_categories",
  title: "List categories",
  description: "List the signed-in user's spending categories and their optional monthly budget.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("categories").select("id, name, color, budget").order("name");
    if (error) return fail(error.message);
    return ok({ categories: data ?? [] });
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";
var list_transactions_default = defineTool3({
  name: "list_transactions",
  title: "List transactions",
  description: "List the signed-in user's transactions, optionally filtered by date range, type, account, category or description text.",
  inputSchema: {
    from: z.string().optional().describe("Inclusive start date, YYYY-MM-DD."),
    to: z.string().optional().describe("Inclusive end date, YYYY-MM-DD."),
    type: z.enum(["income", "expense", "transfer"]).optional(),
    account_id: z.string().uuid().optional(),
    category_id: z.string().uuid().optional(),
    search: z.string().optional().describe("Case-insensitive match on the description."),
    limit: z.number().int().min(1).max(200).optional().describe("Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("transactions").select(
      "id, description, amount, type, transaction_date, value_date, account_id, category_id, refunded_amount, include_in_stats"
    ).order("transaction_date", { ascending: false }).limit(input.limit ?? 50);
    if (input.from) q = q.gte("transaction_date", input.from);
    if (input.to) q = q.lte("transaction_date", input.to);
    if (input.type) q = q.eq("type", input.type);
    if (input.account_id) q = q.eq("account_id", input.account_id);
    if (input.category_id) q = q.eq("category_id", input.category_id);
    if (input.search) q = q.ilike("description", `%${input.search}%`);
    const { data, error } = await q;
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, transactions: data ?? [] });
  }
});

// src/lib/mcp/tools/list-savings-goals.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
var list_savings_goals_default = defineTool4({
  name: "list_savings_goals",
  title: "List savings goals",
  description: "List the signed-in user's savings goals with target amount, current amount and target date.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("savings_goals").select("id, name, target_amount, current_amount, target_date, category").order("target_date", { nullsFirst: false });
    if (error) return fail(error.message);
    return ok({ goals: data ?? [] });
  }
});

// src/lib/mcp/tools/list-upcoming.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_upcoming_default = defineTool5({
  name: "list_upcoming",
  title: "List upcoming commitments",
  description: "List the signed-in user's active recurring transactions and open debts, so an assistant can see what is scheduled ahead.",
  inputSchema: {
    before: z2.string().optional().describe("Only recurring items due on or before this date, YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ before }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let recurring = supabase.from("recurring_transactions").select("id, description, amount, type, recurrence_type, next_due_date, account_id, category_id").eq("is_active", true).order("next_due_date");
    if (before) recurring = recurring.lte("next_due_date", before);
    const [{ data: rec, error: recErr }, { data: debts, error: debtErr }] = await Promise.all([
      recurring,
      supabase.from("debts").select("id, description, type, total_amount, remaining_amount, end_date, contact_name").eq("status", "active")
    ]);
    if (recErr) return fail(recErr.message);
    if (debtErr) return fail(debtErr.message);
    return ok({ recurring: rec ?? [], debts: debts ?? [] });
  }
});

// src/lib/mcp/tools/spending-summary.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";

// src/lib/reportsEngine.ts
import { isWithinInterval } from "npm:date-fns@^3.6.0";

// src/lib/dateUtils.ts
import { startOfDay, endOfDay } from "npm:date-fns@^3.6.0";

// src/lib/reportsEngine.ts
var netExpenseAmount = (t) => Number(t.amount) - Number(t.refunded_amount || 0);
var netIncomeAmount = (t) => Math.max(0, Number(t.amount) - Number(t.repaid_amount || 0));
var periodContribution = (t) => {
  const ignored = { role: "ignored", amount: 0 };
  if (t.include_in_stats === false) return ignored;
  if (t.type === "income") {
    if (t.refund_of_transaction_id) return ignored;
    if (t.offsets_category) return { role: "expense", amount: -netIncomeAmount(t) };
    return { role: "income", amount: netIncomeAmount(t) };
  }
  if (t.type === "expense") {
    if (t.repayment_of_transaction_id) return ignored;
    return { role: "expense", amount: netExpenseAmount(t) };
  }
  if (t.type === "transfer") return { role: "transfer_fee", amount: Number(t.transfer_fee || 0) };
  return ignored;
};

// src/lib/mcp/tools/spending-summary.ts
var round2 = (n) => Math.round(n * 100) / 100;
var spending_summary_default = defineTool6({
  name: "spending_summary",
  title: "Spending summary",
  description: "Summarize income, expenses and net flow over a date range, broken down by category. Expenses are net of refunds and of income the user marked as having come back on a category; income is net of anything repaid against it. Advance settlements and refund rows are excluded \u2014 they would otherwise count the same money twice. Nothing further should be subtracted from these figures.",
  inputSchema: {
    from: z3.string().describe("Inclusive start date, YYYY-MM-DD."),
    to: z3.string().describe("Inclusive end date, YYYY-MM-DD."),
    include_excluded: z3.boolean().optional().describe("Include transactions flagged as excluded from statistics. Default false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, include_excluded }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const COLUMNS = "amount, type, category_id, refunded_amount, repaid_amount, include_in_stats, refund_of_transaction_id, repayment_of_transaction_id, offsets_category, transfer_fee";
    const PAGE = 1e3;
    const page = (offset) => supabase.from("transactions").select(COLUMNS, offset === 0 ? { count: "exact" } : void 0).gte("transaction_date", from).lte("transaction_date", to).order("transaction_date", { ascending: true }).order("id", { ascending: true }).range(offset, offset + PAGE - 1);
    const [first, { data: cats }] = await Promise.all([
      page(0),
      supabase.from("categories").select("id, name")
    ]);
    if (first.error) return fail(first.error.message);
    const tx = [...first.data ?? []];
    const total = first.count ?? tx.length;
    for (let offset = tx.length; tx.length < total && offset < total; offset = tx.length) {
      const next = await page(offset);
      if (next.error) return fail(next.error.message);
      if (!next.data?.length) break;
      tx.push(...next.data);
    }
    const names = new Map((cats ?? []).map((c) => [c.id, c.name]));
    let income = 0;
    let expenses = 0;
    let transferFees = 0;
    const byCategory = /* @__PURE__ */ new Map();
    for (const raw of tx) {
      const t = include_excluded ? { ...raw, include_in_stats: true } : raw;
      const { role, amount } = periodContribution(t);
      if (role === "ignored") continue;
      if (role === "income") income += amount;
      else if (role === "transfer_fee") transferFees += amount;
      else {
        expenses += amount;
        const key = t.category_id ? names.get(t.category_id) ?? "Unknown" : "Uncategorized";
        byCategory.set(key, (byCategory.get(key) ?? 0) + amount);
      }
    }
    return ok({
      period: { from, to },
      income: round2(income),
      expenses: round2(expenses),
      transfer_fees: round2(transferFees),
      net: round2(income - expenses - transferFees),
      by_category: [...byCategory.entries()].map(([category, amount]) => ({ category, amount: round2(amount) })).sort((a, b) => b.amount - a.amount)
    });
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var create_transaction_default = defineTool7({
  name: "create_transaction",
  title: "Create transaction",
  description: "Record a new income or expense transaction on one of the signed-in user's accounts.",
  inputSchema: {
    account_id: z4.string().uuid().describe("Target account, from list_accounts."),
    amount: z4.number().positive().describe("Positive amount in the account currency."),
    type: z4.enum(["income", "expense"]),
    description: z4.string().trim().min(1).max(255),
    transaction_date: z4.string().describe("Accounting date, YYYY-MM-DD."),
    value_date: z4.string().optional().describe("Value date, YYYY-MM-DD. Defaults to the accounting date."),
    category_id: z4.string().uuid().optional().describe("Category, from list_categories.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("transactions").insert({
      user_id: ctx.getUserId(),
      account_id: input.account_id,
      amount: input.amount,
      type: input.type,
      description: input.description,
      transaction_date: input.transaction_date,
      value_date: input.value_date ?? input.transaction_date,
      category_id: input.category_id ?? null
    }).select("id, description, amount, type, transaction_date, category_id").single();
    if (error) return fail(error.message);
    return ok({ transaction: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "cuanladihtpvkmjhvrln";
var mcp_default = defineMcp({
  name: "spendingtrackerjmrvy",
  title: "spendingtrackerjmrvy",
  version: "0.1.0",
  instructions: "Tools for a personal finance tracker. Read the signed-in user's bank accounts, categories, transactions, savings goals and upcoming commitments, summarize spending over a period, and record new income or expense transactions. Amounts are already netted: refunds are inside the expense they refund, repayments inside the income they settle, and money the user marked as having come back on a category reduces that category. Never subtract a refund or repayment yourself. Dates are YYYY-MM-DD.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_accounts_default,
    list_categories_default,
    list_transactions_default,
    list_savings_goals_default,
    list_upcoming_default,
    spending_summary_default,
    create_transaction_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
