// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuanladihtpvkmjhvrln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1YW5sYWRpaHRwdmttamh2cmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDM1NDUsImV4cCI6MjA3MzE3OTU0NX0.Og9jTCPVr-_yNtzuvt22TMVWMxOiQo5jp0I87L6WY7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});